{% set name = "great_tables" %}
{% set version = "0.15.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0d37e5fdde4bd3d21290945f3de6b00410abca05e46a045cdda9259eaa8f590

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
    - wheel
  run:
    - python >={{ python_min }}
    - commonmark >=0.9.1
    - htmltools >=0.4.1
    - importlib-metadata
    - typing_extensions >=3.10.0.0
    - numpy >=1.22.4
    - babel >=2.13.1
    - importlib-resources

test:
  imports:
    - great_tables
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/posit-dev/great-tables
  summary: Easily generate information-rich, publication-quality tables from Python.
  doc_url: https://posit-dev.github.io/great-tables/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - thewchan
