{% set name = "great_tables" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/great-tables-{{ version }}.tar.gz
  sha256: 50e4393bc729d03bee896c2dda96f57f0dda083d4409a1aca9f22a985178d33d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - commonmark >=0.9.1
    - htmltools >=0.4.1
    - importlib-metadata
    - typing-extensions >=3.10.0.0
    - packaging >=20.9
    - pandas >=1.4.2
    - numpy >=1.22.4
    - babel >=2.13.1
    - mizani >=0.9.3
    - webcolors

test:
  imports:
    - great_tables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/posit-dev/great-tables
  summary: Easily generate information-rich, publication-quality tables from Python.
  doc_url: https://posit-dev.github.io/great-tables/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - thewchan
